##
# colors.sh
#
# set the hostname in the prompt to a color based on hostname
#

##
# colors vars
# 
# used for ls and prompt colors
#
NORMAL="0"
BRIGHT="1"
#FAINT="2"
#ITALIC="3"
UNDERLINE="4"
#BLINK="5"
#BLINK_FAST="6"
INVERT="7"
CONCEAL="8"
#STRIKE="9"

BLACK="30"
RED="31"
GREEN="32"
YELLOW="33"
BLUE="34"
MAGENTA="35"
CYAN="36"
GRAY="37"

DARK_GRAY="${BRIGHT};${BLACK}"
BRIGHT_BLUE="${BRIGHT};${BLUE}"
BRIGHT_GREEN="${BRIGHT};${GREEN}"
BRIGHT_CYAN="${BRIGHT};${CYAN}"
BRIGHT_PURPLE="${BRIGHT};${MAGENTA}"
BRIGHT_YELLOW="${BRIGHT};${YELLOW}"
BRIGHT_RED="${BRIGHT};${RED}"
WHITE="${BRIGHT};${GRAY}"

##
# ls colors
#

# standard generic file kind colors

LS_COLORS="no=${NORMAL}"					# normal text (everything but filenames)
LS_COLORS="$LS_COLORS:fi=${NORMAL}"			# regular file
LS_COLORS="$LS_COLORS:di=${BLUE}"	# directory
LS_COLORS="$LS_COLORS:ln=${CYAN}"			# symbolic link
LS_COLORS="$LS_COLORS:pi=${YELLOW}"			# named pipe
LS_COLORS="$LS_COLORS:so=${BRIGHT_PURPLE}"	# socket
LS_COLORS="$LS_COLORS:do=${BRIGHT_PURPLE}"	# door
LS_COLORS="$LS_COLORS:bd=${YELLOW}"			# block device
LS_COLORS="$LS_COLORS:cd=${YELLOW}"			# character device
LS_COLORS="$LS_COLORS:or=${BRIGHT_RED}"		# orphaned symbolic link
LS_COLORS="$LS_COLORS:ex=${BRIGHT_GREEN}"	# executable file

# color by file extension

# archives
LS_COLORS="$LS_COLORS:*.tar=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.tgz=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.arj=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.taz=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.lzh=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.zip=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.z=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.Z=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.gz=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.bz2=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.deb=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.rpm=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.jar=${BRIGHT_RED}"
LS_COLORS="$LS_COLORS:*.rar=${BRIGHT_RED}"

# images
LS_COLORS="$LS_COLORS:*.jpg=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.jpeg=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.gif=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.bmp=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.pbm=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.pgm=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.ppm=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.tga=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.xbm=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.xpm=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.tif=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.tiff=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.png=${BRIGHT_PURPLE}"

# video
LS_COLORS="$LS_COLORS:*.mpg=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.mpeg=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.avi=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.fli=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.gl=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.dl=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.xcf=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.xwd=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.mp4=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.asf=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.qt=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.mov=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.wmv=${BRIGHT_PURPLE}"

# audio
LS_COLORS="$LS_COLORS:*.ogg=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.mp3=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.wav=${BRIGHT_PURPLE}"
LS_COLORS="$LS_COLORS:*.wma=${BRIGHT_PURPLE}"

export LS_COLORS